services:
  eshopdb:
    image: postgres:latest

  distributedcache:
    image: redis:latest

  seq:
    image: datalust/seq:latest

  messagebus:
    image: rabbitmq:management

volumes:
  postgres_eshopdb:

