services:
  eshopdb:
    image: postgres:latest

  distributedcache:
    image: redis:latest

  seq:
    image: datalust/seq:latest

  messagebus:
    image: rabbitmq:management

  identity:
    image: quay.io/keycloak/keycloak:24.0.3

  api:
    image: api
    build:
      context: .
      dockerfile: Bootstrapper/Api/Dockerfile

volumes:
  postgres_eshopdb: